# Generated by Django 3.2 on 2021-04-30 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation datetime', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Update datetime', null=True, verbose_name='Updated at')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
