# Generated by Django 3.2 on 2021-05-03 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0002_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='External Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation datetime', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Update datetime', null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('datetime', models.DateTimeField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
